2024-10-23 21:29:51,829 -|- WARNING -|- Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\olgaa\PycharmProjects\pythonProject1\tests_12_4.py", line 22, in test_run
    runner_2 = r.Runner(10, 10)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\olgaa\PycharmProjects\pythonProject1\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-23 21:29:51,832 -|- WARNING -|- Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\olgaa\PycharmProjects\pythonProject1\tests_12_4.py", line 12, in test_walk
    runner_1 = r.Runner('Данил', -10)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olgaa\PycharmProjects\pythonProject1\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
